# Publish as a Python Package to PyPI when a release is created
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cardamom
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install packaging tools
        run: pip install build
      - name: Build Python package
        run: python -m build
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
